# This is a sample config file for training a model on the mydesk dataset at global batch size 32 (on 8 A100 GPUs).
# It should get around 29 PSNR for evaluation after 8k steps.
# Remember to switch to 1 GPU for evaluation as there is only 1 scene in this dataset.
# For training on the DL3DV dataset with 32 input views, use global batch size 256.
# You can achieve this by setting batch_size_per_gpu or grad_accum_steps, or increasing the number of GPUs. 

data:
  data_path: "data/example_data/mydesk.txt"
  resize_h: 256
  square_crop: true
  input_frame_select_type: "uniform"
  target_frame_select_type: "random"
  num_input_frames: 32
  num_target_frames: 8
  target_has_input: true
  min_frame_dist: 64
  max_frame_dist: 128
  shuffle_input_prob: 0.5
  reverse_input_prob: 0.5

data_eval:
  target_frame_select_type: "uniform"
  target_has_input: false
  min_frame_dist: 96
  max_frame_dist: 96
  shuffle_input_prob: 0.0
  reverse_input_prob: 0.0

training:
  train_steps: 100000
  batch_size_per_gpu: 1
  grad_accum_steps: 4